fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: 'force'
    routing_loader: false
    exception:
        enabled: true
