sonata_admin:
    title: 'Mon admin'
    templates:
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'
    dashboard:
        groups:
            sonata.admin.group.content:
                label: Utilisateurs
                items:
                    - App\Admin\UserAdmin
    security:
        handler: App\Security\SonataAdminSecurityHandler
